#platform :ios, '13.0'

target 'Around Egypt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    use_modular_headers!

    pod 'Alamofire'
    pod 'Kingfisher'

    target 'Around EgyptUnitTests' do
      inherit! :search_paths      # ✅ allows test target to access same pods
    end
end
