#platform :ios, '13.0'

target 'Around Egypt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Around Egypt

  pod 'Alamofire'
  pod 'Kingfisher'

end
